export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';

/* FETCH NOTIFICATION */
export const FETCH_LIST_NOTIFICATION = 'FECH_LIST_NOTIFICATION';
export const FETCH_LIST_NOTIFICATION_SUCCESS = 'FECH_LIST_NOTIFICATION_SUCCESS';
export const FETCH_LIST_NOTIFICATION_FAIL = 'FECH_LIST_NOTIFICATION_FAIL';
export const RESET_FETCH_NOTIFICATION = 'RESET_FETCH_NOTIFICATION';
export const TOGGLE_CHECKBOX_NOTIFICATION = 'TOGGLE_CHECKBOX_NOTIFICATION';

/* CREATE NOTIFICATION */
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS';
export const CREATE_NOTIFICATION_FAIL = 'CREATE_NOTIFICATION_FAIL';

/* UPDATE NOTIFICATION */
export const FETCH_ITEM_NOTIFICATION = 'FETCH_ITEM_NOTIFICATION';
export const FETCH_ITEM_NOTIFICATION_SUCCESS = 'FETCH_ITEM_NOTIFICATION_SUCCESS';
export const FETCH_ITEM_NOTIFICATION_FAIL = 'FETCH_ITEM_NOTIFICATION_FAIL';

export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_FAIL = 'UPDATE_NOTIFICATION_FAIL';

/* DELETE NOTIFICATION */
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAIL = 'DELETE_NOTIFICATION_FAIL';